name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: | 
          pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
          cache-dependency-path: |
            pyproject.toml

      - run: |
          poetry --version

      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }}
          poetry install -E pyscf

      - name: Test with pytest
        run: |
          poetry run pytest 
